apiVersion: v1
kind: Service
metadata:
  name: {{ include "helloWeb3.fullname" . }}
  labels:
    {{- include "helloWeb3.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "helloWeb3.selectorLabels" . | nindent 4 }}
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "helloWeb3.fullname" . }}
#   labels:
#     {{- include "helloWeb3.labels" . | nindent 4 }}
# spec:
#   type: {{ .Values.service.type }}
#   ports:
#     - port: {{ .Values.service.port }}
#       targetPort: http
#       protocol: TCP
#       name: http
#   selector:
#     {{- include "helloWeb3.selectorLabels" . | nindent 4 }}
