name: Build and Push to Artifact Registry

on:
  push:
    tags:
      - 'v*.*.*'  # This pattern matches tags like v1.0.0, v2.1.3, etc.

env:
  PROJECT_ID: ${{ vars.GOOGLE_PROJECT_ID }}
  REGION: us
  ARTIFACT_REGISTRY_NAME: ${{ vars.GOOGLE_ARTIFACT_REGISTRY_NAME }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
  DOCKER_BUILD_CONTEXT: "."
  DOCKERFILE_PATH: "Dockerfile.polygon"

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:

      - name: "Checkout"
        uses: "actions/checkout@v4"

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ env.SERVICE_ACCOUNT_KEY }}"

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Set FULL_IMAGE_NAME"
        run: echo "FULL_IMAGE_NAME=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_NAME }}" >> $GITHUB_ENV

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build . --file ${{ env.DOCKERFILE_PATH }} --tag ${{ env.FULL_IMAGE_NAME }}

      - name: Tag image with version
        run: docker tag ${{ env.FULL_IMAGE_NAME }} ${{ env.FULL_IMAGE_NAME }}:${{ github.ref_name }}

      - name: Push image
        run: docker push ${{ env.FULL_IMAGE_NAME }}

      # - id: docker-push-tagged
      #   name: Tag Docker image and push to Google Artifact Registry
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: |
      #         ${{ env.FULL_IMAGE_NAME }}:${{ github.ref_name }}
      #        <your-gar-region>-docker.pkg.dev/<your-project-id>/<your-gar-repo-name>/<your-docker-image-name>:latest